#!/usr/bin/env bash
# This file is part of DevOrSysAdminScripts library.
#
# DevOrSysAdminScripts is free software:
# you can redistribute it and/or modify it under the terms
# of the GNU General Public License
# as published by the Free Software Foundation,
# either version 3 of the License,
# or (at your option) any later version.
#
# DevOrSysAdminScripts is distributed in the hope
# that it will be useful,
# but WITHOUT ANY WARRANTY;
# without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of
# the GNU General Public License
# along with DevOrSysAdminScripts.
# If not, see <https://www.gnu.org/licenses/>.
#
# ©Copyright 2023-2024 Laurent Frédéric Bernard François Lyaudet
# 2024-05-31T01:49+02:00: This file was renamed from
# "post-commit"
# to
# "post-commit".
# 2024-05-31T01:49+02:00: This file was moved from
# "."
# to
# "./git_helpers".

LFBFL_some_directory="../DevOrSysAdminScripts"
declare -i LFBFL_i_pushd_result3
pushd "${LFBFL_some_directory}" || {
  LFBFL_i_pushd_result3=$?
  printf "post-commit no such directory\n"
  # shellcheck disable=SC2248
  exit ${LFBFL_i_pushd_result3}
}
# shellcheck source=post_commit_renaming_comment.libr.sh
source "./git_helpers/post_commit_renaming_comment.libr.sh"
# shellcheck source=lines_filters.libr.sh
source "./build_and_checks_dependencies/lines_filters.libr.sh"
declare -i LFBFL_i_popd_result3
popd || {
  LFBFL_i_popd_result3=$?
  printf "post-commit no popd\n"
  # shellcheck disable=SC2248
  exit ${LFBFL_i_popd_result3}
}

LFBFL_data_file_name="build_and_checks_variables/repository_data.txt"
LFBFL_max_comment_line_length=""
if [[ -f "${LFBFL_data_file_name}" ]]; then
  LFBFL_max_line_length=""
  grep_variable "${LFBFL_data_file_name}" "max_line_length"\
    --result-variable-prefix="LFBFL_"
  LFBFL_max_comment_line_length="--max-comment-line-length="
  LFBFL_max_comment_line_length+="${LFBFL_max_line_length}"
fi

commit_a_file_renamed_comment --verbose --log-directory-change\
  "${LFBFL_max_comment_line_length}"
exit 0
