#!/usr/bin/env bash
# This file is part of DevOrSysAdminScripts library.
#
# DevOrSysAdminScripts is free software:
# you can redistribute it and/or modify it under the terms
# of the GNU General Public License
# as published by the Free Software Foundation,
# either version 3 of the License,
# or (at your option) any later version.
#
# DevOrSysAdminScripts is distributed in the hope
# that it will be useful,
# but WITHOUT ANY WARRANTY;
# without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of
# the GNU General Public License
# along with DevOrSysAdminScripts.
# If not, see <https://www.gnu.org/licenses/>.
#
# ©Copyright 2023-2024 Laurent Frédéric Bernard François Lyaudet
# 2024-05-31T01:57+02:00: This file was renamed from
# "pre-commit"
# to
# "pre-commit".
# 2024-05-31T01:57+02:00: This file was moved from
# "."
# to
# "./git_helpers".

LFBFL_some_directory="../DevOrSysAdminScripts"
declare -i LFBFL_i_pushd_result3
pushd "${LFBFL_some_directory}" || {
  LFBFL_i_pushd_result3=$?
  printf "pre-commit no such directory\n"
  # shellcheck disable=SC2248
  exit ${LFBFL_i_pushd_result3}
}
# shellcheck source=git_checks.libr.sh
source "./git_helpers/git_checks.libr.sh"
declare -i LFBFL_i_popd_result3
popd || {
  LFBFL_i_popd_result3=$?
  printf "pre-commit no popd\n"
  # shellcheck disable=SC2248
  exit ${LFBFL_i_popd_result3}
}

declare -gi LFBFL_i_git_hook_error=0
if ! check_files; then
  LFBFL_i_git_hook_error=1
fi
if ! check_no_abusive_trailing_comma; then
  LFBFL_i_git_hook_error=1
fi
if ! check_black_code_formatting; then
  LFBFL_i_git_hook_error=1
fi
readonly LFBFL_i_git_hook_error
# shellcheck disable=SC2248
exit ${LFBFL_i_git_hook_error}
