#!/usr/bin/env bash
# This file is part of DevOrSysAdminScripts library.
#
# DevOrSysAdminScripts is free software:
# you can redistribute it and/or modify it under the terms
# of the GNU General Public License
# as published by the Free Software Foundation,
# either version 3 of the License,
# or (at your option) any later version.
#
# DevOrSysAdminScripts is distributed in the hope
# that it will be useful,
# but WITHOUT ANY WARRANTY;
# without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of
# the GNU General Public License
# along with DevOrSysAdminScripts.
# If not, see <https://www.gnu.org/licenses/>.
#
# ©Copyright 2023-2024 Laurent Frédéric Bernard François Lyaudet
# 2024-05-31T01:57+02:00: This file was renamed from
# "pre-commit"
# to
# "pre-commit".
# 2024-05-31T01:57+02:00: This file was moved from
# "."
# to
# "./git_helpers".

LFBFL_library="../DevOrSysAdminScripts/git_helpers/"
LFBFL_library+="git_checks.libr.sh"
# shellcheck disable=SC1090
source "${LFBFL_library}"

declare -ig LFBFL_git_hook_error=0
if ! check_files; then
  LFBFL_git_hook_error=1
fi
if ! check_no_abusive_trailing_comma; then
  LFBFL_git_hook_error=1
fi
if ! check_black_code_formatting; then
  LFBFL_git_hook_error=1
fi
readonly LFBFL_git_hook_error
if [[ LFBFL_git_hook_error -eq 1 ]]; then
  exit 1
fi
exit 0
